services:
  nginx:
    image: nginx:1.28.0-alpine3.21-slim
    ports:
      - "80:80"
    volumes:
      - ./config.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/app/
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./src/:/app/
    env_file:
      - ./example.env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./example.env

volumes:
  postgres_data: