services:
  nginx:
    image: nginx:1.28.0-alpine3.21-slim
    ports:
      - "80:80"
    volumes:
      - ./config.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/app/index.php
    depends_on:
      - php

  php:
    image: php:8.4.7-fpm-alpine3.21
    volumes:
      - ./index.php:/app/index.php